"""Tier 2 pipeline orchestration (Step 7).

Wires already-built Steps 1–5b into one entry point. Does not reimplement their
logic. Step 6 labeling is injected (defaults to the placeholder in labeling.py).
Does not write to any database — returns objects for the orchestration layer.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Callable

from secondlook.alphamissense import lookup_alphamissense
from secondlook.binding import score_binding
from secondlook.candidates import generate_candidates
from secondlook.labeling import label_binding_score
from secondlook.mutation_validation import validate_mutation
from secondlook.structure import source_structure
from secondlook.uniprot import UniProtLookupError

PIPELINE_VERSION = "0.1.0"

TIER2_DISCLAIMER = (
    "This is a computational plausibility signal generated by structural prediction tools for research "
    "and hypothesis-generation only. It is not clinical evidence, a diagnosis, or a treatment "
    "recommendation, and it has not been clinically validated for this mutation. The underlying models "
    "predict physical binding/stability changes with limited accuracy and were not designed to predict "
    "patient response. These results must be interpreted by a qualified clinician alongside established "
    "evidence before any clinical decision. Do not use this output to start, stop, or change any "
    "treatment."
)

TIMEOUT_API_ERROR_MESSAGE = (
    "Tier 2 analysis could not complete (timeout/error). No partial or inferred result is shown "
    "to avoid misleading output. Please retry or consult evidence-based resources."
)

LabelingFn = Callable[[float | None], str]


@dataclass(frozen=True)
class Tier2PipelineResult:
    items: tuple[dict, ...] = ()
    failure: dict | None = None


def run_tier2_pipeline(
    identifier: str,
    mutation: str,
    *,
    sequence_provider=None,
    transcript_resolver=None,
    vep_client=None,
    pdb_client=None,
    alphafold_client=None,
    esm_client=None,
    dgidb_client=None,
    opentargets_client=None,
    chembl_client=None,
    pubchem_client=None,
    mcsm_client=None,
    vina_client=None,
    het_resolver=None,
    min_delay_seconds: float = 3.0,
    sleeper=None,
    max_candidates: int = 20,
    labeling_fn: LabelingFn | None = None,
) -> Tier2PipelineResult:
    """Run Steps 1→5b for one mutation and assemble api-contracts.md items.

    ESM Atlas is never on this path: allow_de_novo_folding stays False.
    Binding scores are computed serially so mCSM-lig's min_delay_seconds is real.
    """
    if labeling_fn is None:
        labeling_fn = label_binding_score

    try:
        validation = validate_mutation(
            identifier, mutation, sequence_provider=sequence_provider
        )
    except UniProtLookupError:
        return _failure(TIMEOUT_API_ERROR_MESSAGE, retryable=True)

    if validation.status != "valid":
        return _failure(validation.error_message or TIMEOUT_API_ERROR_MESSAGE, retryable=False)

    alphamissense = lookup_alphamissense(
        validation,
        transcript_resolver=transcript_resolver,
        vep_client=vep_client,
    )

    structure = source_structure(
        validation,
        pdb_client=pdb_client,
        alphafold_client=alphafold_client,
        esm_client=esm_client,
        allow_de_novo_folding=False,
    )

    candidates = generate_candidates(
        validation,
        dgidb_client=dgidb_client,
        opentargets_client=opentargets_client,
        chembl_client=chembl_client,
        pubchem_client=pubchem_client,
        max_candidates=max_candidates,
    )
    if candidates.status == "none":
        return _failure(candidates.error_message or TIMEOUT_API_ERROR_MESSAGE, retryable=False)

    items = []
    for candidate in candidates.candidates:
        binding = score_binding(
            validation,
            structure,
            candidate,
            mcsm_client=mcsm_client,
            vina_client=vina_client,
            het_resolver=het_resolver,
            min_delay_seconds=min_delay_seconds,
            sleeper=sleeper,
        )
        items.append(
            _result_item(
                validation=validation,
                alphamissense=alphamissense,
                structure=structure,
                candidate=candidate,
                binding=binding,
                labeling_fn=labeling_fn,
            )
        )
    return Tier2PipelineResult(items=tuple(items), failure=None)


def to_structural_signal(item: dict) -> dict:
    """Shape one result item as a StructuralSignal for the Tier 1 graph loader.

    Does not write to any database.
    """
    alphamissense = item.get("alphamissense") or {}
    structure = item.get("structure") or {}
    return {
        "alphamissense_score": alphamissense.get("score"),
        "alphamissense_class": alphamissense.get("class"),
        "structure_source": structure.get("source"),
        "structure_id": structure.get("id"),
        "plddt_at_residue": structure.get("plddt_at_residue"),
        "reliability_flag": structure.get("reliability_flag"),
        "method": item.get("method"),
        "binding_site_distance_angstrom": item.get("binding_site_distance_angstrom"),
        "computed_at": datetime.now(timezone.utc).isoformat(),
        "pipeline_version": PIPELINE_VERSION,
    }


def _result_item(
    *,
    validation,
    alphamissense,
    structure,
    candidate,
    binding,
    labeling_fn: LabelingFn,
) -> dict:
    unavailable = binding.status == "unavailable"
    return {
        "type": "computational_signal",
        "mutation_validated": asdict(validation),
        "alphamissense": {
            "score": alphamissense.am_pathogenicity,
            "class": alphamissense.am_class,
        },
        "structure": {
            "source": structure.source,
            "id": structure.id,
            "plddt_at_residue": structure.plddt_at_residue,
            "reliability_flag": structure.reliability_flag,
        },
        "drug": candidate.name,
        "smiles_source": candidate.smiles_source,
        "method": None if unavailable else binding.method,
        "delta_score": None if unavailable else binding.delta_score,
        "label": None if unavailable else labeling_fn(binding.delta_score),
        "binding_site_distance_angstrom": binding.distance_angstrom,
        "disclaimer": TIER2_DISCLAIMER,
        "binding_note": binding.error_message if unavailable else None,
    }


def _failure(reason: str, *, retryable: bool) -> Tier2PipelineResult:
    return Tier2PipelineResult(
        items=(),
        failure={
            "type": "failure",
            "tier": "2",
            "reason": reason,
            "retryable": retryable,
        },
    )
